services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8181:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
    volumes:
      - weaviate-data:/var/lib/weaviate

volumes:
  weaviate-data:
