
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: boooks123
      POSTGRES_HOST_AUTH_METHOD: trust # Allow connections from all hosts
    ports:
      - 5432:5432
    command: postgres -c listen_addresses='*' # Listen on all interfaces

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

